stages:
  - build
  - deploy


build_linux:
  stage: build
 
  script:
    - make
    - ./ci/deploy_build.sh linux_build
  artifacts:
    when: on_success
    paths: 
      - assets/
      - tower
    expire_in: 1 week


build_emscripten:
  stage: build
  
  script:
    - source $EMSDK/emsdk_env.sh
    - make CXX=em++
    - ./ci/deploy_build.sh emscripten_build
  artifacts:
    when: on_success
    paths: 
      - assets/
      - "*.js"
      - "*.html"
      - "*.data"
      - "*.wasm"
    expire_in: 1 week


build_windows:
  stage: build
  
  script:
    - make CXX=x86_64-w64-mingw32-g++
    - ./ci/deploy_build.sh windows_build
  artifacts:
    when: on_success
    paths: 
      - assets/
      - "*.exe"
    expire_in: 2 week
